gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - underline
      - bold
    selectedRangeBgColor:
      - reverse
keybinding:
  universal:
    quit: 'q'
    quit-alt1: 'q'  # alternative/alias of quit
    return: '<c-c>'  # return to previous menu, will quit if there's nowhere to return
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'  # goto the next panel
    prevItem: '<up>'  # go one line up
    nextItem: '<down>'  # go one line down
    prevItem-alt: 'k'  # go one line up
    nextItem-alt: 'j'  # go one line down
    prevPage: ','  # go to next page in list
    nextPage: '.'  # go to previous page in list
    gotoTop: '<'  # go to top of list
    gotoBottom: '>'  # go to bottom of list
    scrollLeft: 'H'  # scroll left within list view
    scrollRight: 'L'  # scroll right within list view
    prevBlock: '<left>'  # goto the previous block / panel
    nextBlock: '<right>'  # goto the next block / panel
    prevBlock-alt: 'h'  # goto the previous block / panel
    nextBlock-alt: 'l'  # goto the next block / panel
    jumpToBlock: ['1', '2', '3', '4', '5']  # goto the Nth block / panel
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu: 'x'  # show help menu
    optionMenu-alt1: '?'  # show help menu
    select: '<space>'
    goInto: '<enter>'
    openRecentRepos: '<c-r>'
    confirm: '<enter>'
    confirm-alt1: 'y'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'  # main panel scroll up
    scrollDownMain: '<pgdown>'  # main panel scroll down
    scrollUpMain-alt1: 'K'  # main panel scroll up
    scrollDownMain-alt1: 'J'  # main panel scroll down
    scrollUpMain-alt2: '<c-u>'  # main panel scroll up
    scrollDownMain-alt2: '<c-d>'  # main panel scroll down
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'  # deprecated
    copyToClipboard: '<c-o>'
    submitEditorText: '<enter>'
    appendNewline: '<a-enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'  # commit changes without pre-commit hook
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'  # stage/unstage all
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'  # fast-forward this branch from its upstream
    pushTag: 'P'
    setUpstream: 'u'  # set as upstream of checked-out branch
    fetchRemote: 'f'
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'  # create fixup commit for this commit
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'  # move commit down one
    moveUpCommit: '<c-k>'  # move commit up one
    amendToCommit: 'A'
    pickCommit: 'p'  # pick commit (when mid-rebase)
    revertCommit: 't'
    cherryPickCopy: 'c'
    cherryPickCopyRange: 'C'
    pasteCommits: 'v'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitMessageToClipboard: '<c-y>'
    openLogMenu: '<c-l>'
    viewBisectOptions: 'b'
  stash:
    popStash: 'g'
  commitFiles:
    checkoutCommitFile: 'c'
  main:
    toggleDragSelect: 'v'
    toggleDragSelect-alt: 'V'
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
