---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
  braces:
    max-spaces-inside: 1
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
  line-length:
    max: 120
